# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Client\EmbedderClient:
        arguments:
            $baseUrl: '%env(string:EMBEDDER_URL)%'

    App\Service\Client\ChromaClient:
        arguments:
            $baseUrl: '%env(string:CHROMA_URL)%'

    App\Service\Client\QdrantClient:
        arguments:
            $baseUrl: '%env(string:QDRANT_URL)%'

    App\Service\Client\FaissClient:
        arguments:
            $baseUrl: '%env(string:FAISS_URL)%'

    App\Service\Client\OllamaClient:
        arguments:
            $baseUrl: '%env(string:OLLAMA_URL)%'

